name: .NET Core Desktop

on:
  push:
    branches: [ "Development" ]
  pull_request:
    branches: [ "Development" ]  
    
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug]

    env:
      Solution_Name: GenericProject.sln  
      Test_Project_Path: GenericMaui.TestXUnit\GenericMaui.TestXUnit.csproj

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Configurar MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Rodar testes unitários
        run: dotnet test ${{ env.Test_Project_Path }}

  merge-to-main:
    needs: build
    runs-on: windows-latest
    if: success()  # Só executa se os testes passarem

    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Garante que todo o histórico do repositório seja baixado
          token: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Configurar usuário Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Criar merge do development → main
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff Development -m "Merge automático do branch development"
          git push origin main
